ericgio/react-bootstrap-typeahead

package.json
Versions of `react-onclickoutside` below `5.3.3` may cause react bind errors:
`You are binding a component method to the component. React does this for you automatically in a high-performance way, so you can safely remove this call. See Typeahead`
(npm was installing `react-onclickoutside@5.3.2` for me, which was causing these errors ): )
=> upgrade react-onclickoutside to 5.3.3

src/MenuItem.react.js
this fixes a bug where selecting a menu item by clicking on it behaves differently than selecting the same menu item by hitting the enter key on the keyboard.
=> bugfix: dont use a href

package.json, src/containers/tokenBehaviors.js
As of v.5.7.0. onclickoutside adds two additional properties `disableOnClickOutside` and `enableOnClickOutside` to a wrapped component. This leads to an unsupported property warning while spreading these props to a Token div container.
Basically this fix is doing the following:
1. Omits `disableOnClickOutside` and `enableOnClickOutside` from component props
2. Utilizes this new feature by enabling and disabling onclickoutside on token focus and blur
3. Removes `babel` dependency as deprecated.
```
ERROR: 'Warning: Unknown props `disableOnClickOutside`, `enableOnClickOutside` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
in div (created by Token)
in Token (created by Constructor)
in Constructor (created by OnClickOutside(Constructor)) …
```
=> Fix `disableOnClickOutside` and `enableOnClickOutside`

src/TypeaheadInput.react.js
In Chrome (and maybe other browsers) the native auto completion list overlaps with the plugins suggestions.
=> Disabled native browser autocomplete

package.json, src/Overlay.react.js
If the Overlay is mounted at `<body />`, it jitters while page scrolls. This happens because `<Overlay />` is repositioned with throttled call.
To mitigate the jitter issue, replace`throttle` with `raf` (a.k.a `requestAnimationFrame`) instead.
**before**
**after**
=> Make Overlay update its position more smoothly

src/containers/asyncContainer.js
- cancel debounce to avoid 'warning.js:36 Warning: setState(...): Can only update a mounted or mounting component.'
=> cancel searchDebounce in componentWillUnmount

src/HintedInput.react.js
I ran in to this as a problem when using [react-redux-form](https://github.com/davidkpiano/react-redux-form). When it finds an input with the `multiple` attribute it treats it differently.
=> Stop multiple attribute being set on input

src/Overlay.react.js, test/components/OverlaySpec.js
Rather than the overlay throwing an error when it is passed more or less than one child, this allows it to now be passed 0 children as a way of controlling the visibility of the menu without having to pass an empty div, and rendering it + the portal that wraps it.
Passing more than one child results in the same functionality as previously. (thrown error from react)
=> Make sure that `Overlay` can render with empty children

src/containers/inputContainer.js
Even when autocomplete is set to "off", Chrome's autofill overrides this setting. Changing the value to something that does not match will stop all browsers from trying to autocomplete. 
Source: [MDN Web Docs: How to Turn Off Form Autocompletion](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) 
> In some cases, the browser will continue suggesting autocompletion values even if the autocomplete attribute is set to off... The trick to really enforcing non-autocompletion is to assign an invalid value to the attribute, for example: `autocomplete="nope"`. Since this value is not a valid one for the autocomplete attribute, the browser has no way to match it, and stops trying to autocomplete the field.
=> Handle Chrome override of autcomplete="off"

src/containers/asyncContainer.js, test/components/AsyncTypeaheadSpec.js
So after attempting to use the latest build to leverage the allowNew callback option I added, things were working. I dug in and found out that AsyncTypeahead has a condition check with allowNew, so even if allowNew is a function, a boolean is passed from AsyncTypeahead to Typeahead.
I'm not sure if this is the best way to fix it, but I've added a test to verify it works and the existing tests are all fine too.
=> Fixed issue with allowNew callback option not working with async

src/containers/hintContainer.js
> "You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`."
I think this is readOnly but I'm not 100% sure.
=> Fix react 16.5.0 warning

package.json, yarn.lock
(node:25426) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Updating karma-webpack to a release candidate fixed it for me.
Traced it with:
```sh
node --trace-deprecation ./node_modules/.bin/karma start
```
=> Remove Tapable.plugin deprecation warning on karma start

src/containers/typeaheadContainer.js, test/components/TypeaheadSpec.js
When we have list of options for Typeahead component and the last option is disabled we can select this option by hitting UP arrow
=> Fix highlighting of the last option when it's disabled

src/containers/typeaheadContainer.js
Checking the type of `target.className`: on SVG element `target.className` is an object, not a string so `target.className.indexOf` will throw the error `target.className.indexOf is not a function`
=> Fix target.className type error is not a string on SVG element

docs/Props.md
The description of the `filterBy` callback is not clear enough.
I added a description of the arguments and return value expected from this callback.
I don't think so.
=> Make role of filterBy clearer in docs

src/containers/contextContainer.js, test/components/TypeaheadSpec.js
#459
Prevent adding the initial item if it is not truthy
Perhaps it should actually add the only result even though the menu is hidden?
=> Fix combination of open=false and highlightOnlyResult

docs/API.md
fix this error: 
One or more options does not have a valid label string. Check the `labelKey` prop to ensure that it matches the correct option key and provides a string for filtering and display.
=> Fix AsyncTypeahead example code

styles/Typeahead-bs4.scss, styles/Typeahead.scss
As per our conversation in https://github.com/ericgio/react-bootstrap-typeahead/issues/542.
=> Make the style rule for multi-input more specific

README.md
#571 
I've updated the README file and edited the API docs link text to include Props: (API & Props)
No, I don't believe so.
=> #571: update API docs link text to  include Props

styles/Typeahead.scss
The scss file uses non-default variables for configuration. Unfortunately, these cannot be changed from the outside. This PR aims to change this.
The variables were made default and renamed to avoid collisions (I added a `rbt-` prefix).
I'm aware of no such thing.
=> Allow changing colors via SCSS variables

src/types.ts
I opted not to create a GitHub issue for this simple type fix. The issue is that the type of `FilterByCallback` should be `boolean` and currently it is `void`.
Changed the return type of the `FilterByCallback` to `boolean`.
No.
=> Fix filter callback return type

.yarnclean
There is a known issue with storybook that the @emotion/core dependency augments the React `HTMLAttributes` with an additional `css` property. This causes the compiled types of react-bootstrap-typeahead to include that attribute as well, which in turns breaks Typescript compilation of projects using it.
See: https://github.com/emotion-js/emotion/issues/1257#issuecomment-547188357
If possible, please release this in an alpha.10 package soon, as it is currently stopping one of our projects from building.
=> fix: remove @emotion/core types after running yarn

src/components/TypeaheadMenu/TypeaheadMenu.stories.tsx, src/components/TypeaheadMenu/__snapshots__/TypeaheadMenu.test.tsx.snap
One of the tests was using locale specific number formatting, and broke the test when running in a system that is not using a comma as a thousands separator.
=> Tests should not depend on the system locale

src/components/Overlay/Overlay.tsx
#791 
This is a cheap solution that does not improve the performance (it is a non-issue for `Overlay`), but removes the warning without changing the overall design or the unit testing
No
=> `defaultProps` for functional components are deprecated

src/utils/getUpdatedActiveIndex.test.ts, src/utils/getUpdatedActiveIndex.ts
#818
Updated the disabled check used for keyboard selection of options to match the general disabled check for options (previously it was considering the option disabled if it had a property named `disabled`, rather than looking at the value of that property.)
=> don't skip options with a falsey disabled value

src/utils/stripDiacritics.ts
Issue #806
Added Japanese diacritics to the list of diacritics being stripped by the RegExp.
Consider normalizing the resulting string back to NFC before returning from `stripDiacritics`.
If any other diacritics were missed, or if the conversion to NFD caused other decompositions other than diacritics, the NFD string will be longer, causing the highlighting to be offset. Normalizing back to NFC avoids this. This can be done by adding `.normalize('NFC')` on a new line in between line 119 and line 120.
=> Strip Japanese diacritics

docs/API.md
Minor documentation change to isValid and isInvalid props
This current wording mislead me at first to assume this would not work with Bootstrap 5 for some reason;  but it actually does,  so I made that more clear.
(I assume it was originally written before 5 was released)
No
=> make it clearer that isValid and isInvalid work for 5 too

src/components/Overlay/Overlay.test.tsx, src/components/Overlay/useOverlay.ts
#776
I added a popperjs modifier that will disable popperjs from trying to prevent over flow on a menu for options
No
=> Long option causes menu to open in wrong position issue
